# Generated by Django 3.2.6 on 2021-10-18 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='about',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='f_pro',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='know',
        ),
        migrations.DeleteModel(
            name='View_Projects',
        ),
    ]
