# Generated by Django 3.2.6 on 2021-10-18 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20211017_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_view',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.projects')),
            ],
        ),
    ]
