# Generated by Django 3.2.6 on 2021-10-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_project_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Project_view',
        ),
    ]
