# Generated by Django 3.2.6 on 2021-10-19 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20211018_2143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='project_img',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_img',
        ),
    ]
