# Generated by Django 3.2.6 on 2021-10-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20211019_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_i',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
